In [2]:
import numpy as np

In [6]:
a = np.array([1, 2, 3, 4,
              5, 6, 7, 8,
              9, 10, 11, 12])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
x = a.reshape(3, 4)
print(x)
print(a.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
int32


In [12]:
a = np.array([1, 2, '3', True]) # все становится строками, т.е. в массиве должен быть один тип данных
print(a)

['1' '2' '3' 'True']


In [26]:
print(a[0])
print(a[2])

1
3


In [28]:
#запись в массив
a[1] = '123' # обращение как в списке
print(a)

['1' '123' '3' 'True']


In [30]:
a[1] = 234 # тоже преобразует в строку
print(a)

['1' '234' '3' 'True']


In [32]:
a = np.array([1,2,3,4,5,6,7,8,9])

print(a[2])

print(a[ [1,1,1,1,1,1,1,1,1] ])

print(a[ [1,1,1,1,1] ])

3
[2 2 2 2 2 2 2 2 2]
[2 2 2 2 2]


In [34]:
# Если True - возвращает элемент массива
print(a[[True,True,False,False,False,False,True,True,True]])

[1 2 7 8 9]


In [36]:
b = a.reshape(3, 3) # превращает одномерный массив в двумерный
print(b)

print(b[1][2]) # где [1][2] индексы строки и столбца соответственно

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
