## Функции sum, mean, min и max

In [5]:
import numpy as np

In [7]:
a = np.array([ 1,  2,  3, 10, 20, 30])
print(a)

[ 1  2  3 10 20 30]


In [9]:
print(a.sum())

66


In [11]:
print(a.mean())
print(a.max())
print(a.min())

11.0
30
1


In [15]:
a.resize(3, 2)
print(a)

[[ 1  2]
 [ 3 10]
 [20 30]]


In [19]:
print(a.sum(axis = 0))
print(a.sum(axis = 1))

[24 42]
[ 3 13 50]


In [21]:
print(a.max(axis = 0))
print(a.max(axis = 1))

[20 30]
[ 2 10 30]


## Базовые математические функции

In [24]:
a = np.array([-1, 1, 5, -44, 32, 2])
print(a)

[ -1   1   5 -44  32   2]


In [34]:
print(np.abs(a)) # массив
print(np.abs( -10.5)) # число 
print(np.abs([-10.5, -2.5])) #список

[ 1  1  5 44 32  2]
10.5
[10.5  2.5]


In [38]:
print(np.amax(a))
print(np.amin(a))

32
-44


In [42]:
print(np.round(0.7))
print(np.round(a))

1.0
[ -1   1   5 -44  32   2]


In [50]:
print(np.argmax(a)) # возвращает индекс максимального элемента
print(np.argmin(a))

4
3


In [52]:
a.resize(2, 3)
print(a)

[[ -1   1   5]
 [-44  32   2]]


In [56]:
print(np.amax(a, axis = 0))
print(np.amax(a, axis = 1))

[-1 32  5]
[ 5 32]


## Тригонометрические функции

In [59]:
a = np.linspace(0, np.pi, 10)
print(a)

[0.         0.34906585 0.6981317  1.04719755 1.3962634  1.74532925
 2.0943951  2.44346095 2.7925268  3.14159265]


In [65]:
res1 = np.sin(a) # возвращает массив синусов углов
print(res1)
res2 = np.cos(a) # возвращает массив косинусов углов
print(res2)
print(np.arcsin(res1)) # возвращает арксинусы от значений res1

[0.00000000e+00 3.42020143e-01 6.42787610e-01 8.66025404e-01
 9.84807753e-01 9.84807753e-01 8.66025404e-01 6.42787610e-01
 3.42020143e-01 1.22464680e-16]
[ 1.          0.93969262  0.76604444  0.5         0.17364818 -0.17364818
 -0.5        -0.76604444 -0.93969262 -1.        ]
[0.00000000e+00 3.49065850e-01 6.98131701e-01 1.04719755e+00
 1.39626340e+00 1.39626340e+00 1.04719755e+00 6.98131701e-01
 3.49065850e-01 1.22464680e-16]


In [63]:
print(np.sin(np.pi/3))
print(np.cos([0, 1.57, 3.17]))

0.8660254037844386
[ 1.00000000e+00  7.96326711e-04 -9.99596538e-01]


## Функции генерации псевдослучайных чисел

In [ ]:
#Функции rand() и randint() генерируют числа с равномерным законом распределения

In [71]:
print(np.random.rand()) # вещественное случайное число от 0 до 1

0.15617045146251918


In [75]:
print(np.random.rand(5)) # массив таких чисел

[0.31055366 0.39023871 0.49970186 0.06738193 0.24581637]


In [81]:
print(np.random.rand(2, 3)) # Для получения двумерных массивов – два аргумента

[[0.23425944 0.71517193 0.8789326 ]
 [0.97713448 0.36214489 0.76462616]]


In [87]:
print(np.random.randint(10)) # генерация целых чисел в диапазоне [0; 10)

1


In [89]:
print(np.random.randint(5, 10)) # генерация в диапазоне [5; 10)

9


In [ ]:
#Для получения массива из таких случайных чисел дополнительно следует указать параметр size, следующим образом:

In [91]:
print(np.random.randint(5, size = 4))

[4 1 3 3]


In [93]:
print(np.random.randint(1, 10, size = (2, 5)))

[[2 2 5 4 3]
 [3 8 2 1 2]]


In [97]:
print(np.random.randn()) # нормальная СВ с нулевым средним и единичной дисперсией

-1.8390525012327505


In [99]:
print(np.random.randn(5)) # массив из пяти нормальных СВ

[-0.41795881 -1.11124435 -0.98694498  3.00216727  1.58416068]


In [101]:
print(np.random.randn(2, 3)) # матрица 2x3 из нормальных СВ

[[-1.8772452   0.05419302  1.56222811]
 [-1.65198687  0.05592589 -1.12635032]]


По умолчанию, все рассмотренные функции при каждом новом запуске генерируют разные числа. Однако, иногда требуются одни и те же их реализации. Например, такой подход часто используется для сохранения начальных случайных значений весов в нейронных сетях. Для этого устанавливают некое начальное значение зерна (seed):

In [105]:
np.random.seed(1) # начальное значение генератора случайных чисел
np.random.randint(10, size=10)

array([5, 8, 9, 5, 0, 0, 1, 7, 6, 9])

In [107]:
np.random.randint(10, size=10)

array([2, 4, 5, 2, 4, 2, 4, 7, 7, 9])

In [109]:
np.random.seed(1) 

In [111]:
np.random.randint(10, size=10)

array([5, 8, 9, 5, 0, 0, 1, 7, 6, 9])

## Функции перемешивания элементов массива

In [115]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [125]:
np.random.shuffle(a) # перемешивает случайным образом элементы массива. Работает только с первой осью axis0
print(a)

[8 3 1 5 6 0 7 2 4 9]


In [127]:
a = np.arange(1, 10).reshape(3, 3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [129]:
np.random.shuffle(a) # перемешивает только строки
print(a)

[[4 5 6]
 [7 8 9]
 [1 2 3]]


In [133]:
print(np.random.permutation(10)) # возвращает случайную последовательность чисел, генерируя последовательность «на лету»

[4 3 5 6 0 1 8 7 2 9]


## Функции математической статистики

In [142]:
x = np.array([1, 4, 3, 7, 10, 8, 14, 21, 20, 23])
y = np.array([4, 1, 6, 9, 13, 11, 16, 19, 15, 22])

In [144]:
print(np.median(x))

9.0


In [152]:
print(np.var(x)) # дисперсия

57.29


In [150]:
print(np.std(x)) # среднеквадратическое отклонение

7.569015788066504


In [154]:
XY = np.vstack([x, y])
print(XY)

[[ 1  4  3  7 10  8 14 21 20 23]
 [ 4  1  6  9 13 11 16 19 15 22]]


In [158]:
print(np.corrcoef(XY)) #коэффициент корреляции Пирсона

[[1.         0.93158099]
 [0.93158099 1.        ]]


In [162]:
print(np.cov(XY)) # вычисление ковариационной матрицы

[[63.65555556 49.82222222]
 [49.82222222 44.93333333]]


In [166]:
print(np.correlate(x, y))# вычисление кросс-корреляции

[1736]
