In [2]:
import numpy as np

In [4]:
a = np.array([1, 2, 3, 4, 4, 3, 2, 1])

In [6]:
setA = np.unique(a)
print(setA)

[1 2 3 4]


In [8]:
print(np.unique(a, return_counts = True)) #также возвращает число вхождений элементов в исходном массиве a.

(array([1, 2, 3, 4]), array([2, 2, 2, 2], dtype=int64))


In [10]:
print(np.unique(a, return_index = True)) # позволяет определять индексы первого вхождения уникальных элементов

(array([1, 2, 3, 4]), array([0, 1, 2, 3], dtype=int64))


In [12]:
print(np.unique(a, return_inverse = True)) # возвращает индексы

(array([1, 2, 3, 4]), array([0, 1, 2, 3, 3, 2, 1, 0], dtype=int64))


In [14]:
setA, indx = np.unique(a, return_inverse = True)
print(setA)
print(indx)

[1 2 3 4]
[0 1 2 3 3 2 1 0]


In [16]:
print(setA[indx])

[1 2 3 4 4 3 2 1]


In [22]:
x = np.array([[0, 1, 1, 2],[0, 1, 1, 2],[9, 1, 1, 2]])
print(x)
print(np.unique(x)) # array([0, 1, 2, 9])

[[0 1 1 2]
 [0 1 1 2]
 [9 1 1 2]]
[0 1 2 9]


In [20]:
print(np.unique(x, axis = 0)) # возвращает уникальные строки 

[[0 1 1 2]
 [9 1 1 2]]


In [24]:
print(np.unique(x, axis = 1)) # возвращает уникальные столбцы

[[0 1 2]
 [0 1 2]
 [9 1 2]]


## Операции над множествами

In [29]:
x = np.array([0, 1, 2, 3])
y = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(x)
print(y)

[0 1 2 3]
[1 2 3 4 5 6 7 8]


In [31]:
print(np.in1d(x, y)) # показывает, есть ли элемент массива x в массиве y

[False  True  True  True]


In [33]:
print(np.intersect1d(x, y)) # пересечение множеств

[1 2 3]


In [35]:
print(np.union1d(x, y)) # объединение множеств

[0 1 2 3 4 5 6 7 8]


In [39]:
print(np.setdiff1d(x, y)) # вычитание множеств
print(np.setdiff1d(y, x))

[0]
[4 5 6 7 8]


In [43]:
print(np.setxor1d(x, y)) # остаются не совпадающие значения из двух множеств.

[0 4 5 6 7 8]
