In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [6]:
a = np.array([1,2,3,4], 'float') # можно указать поддерживаемый тип данных
print(a)

[1. 2. 3. 4.]


In [8]:
print(np.complex64(10))

(10+0j)


In [10]:
a = np.array([1,2,5000,1000])
print(a)
b = np.complex64(a)
print(b)
c = np.int32(b)
print(c)

[   1    2 5000 1000]
[1.e+00+0.j 2.e+00+0.j 5.e+03+0.j 1.e+03+0.j]
[   1    2 5000 1000]


C:\Users\ryagu\AppData\Local\Temp\ipykernel_5788\3427834974.py:5: ComplexWarning: Casting complex values to real discards the imaginary part
  c = np.int32(b)


In [14]:
a = np.array((1,2,3))
a

array([1, 2, 3])

In [16]:
#Создание двумерной матрицы
a = np.array( [[1, 2], [3, 4], [5, 6]] )
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
#Создание трехмерной матрицы
a = np.array( [ [[1, 2], [3, 4]], [ [5, 6], [7, 8] ], [[9, 10], [11, 12]] ] )
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [22]:
print(a[0])
print(a[0][0])
print(a[0, 0, 0])

[[1 2]
 [3 4]]
[1 2]
1
