In [2]:
import numpy as np

## функции автозаполнения

In [4]:

a = np.array([0] * 10) #генерация массива
print(a)

[0 0 0 0 0 0 0 0 0 0]


In [6]:
a = np.array( [x for x in range (10)] ) #генерация массива через генератор списка
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
b = np.empty(4) # создает одномерный массив со случайными значениями
print(b)
b = np.empty((3,2), dtype= 'int16') # создает массив со случайными значениями
print(b)

[6.23042070e-307 4.67296746e-307 1.69121096e-306 7.56607277e-307]
[[0 0]
 [0 0]
 [0 0]]


In [10]:
e = np.eye(3) # создает единичную матрицу
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
e = np.identity(3) # создает единичную матрицу
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
z = np.zeros([2,3,4]) #создает массив, заполненный нулями
print(z)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [16]:
o = np.ones((2,3), dtype= 'int8') #создает массив, заполненный единицами
print(o)

[[1 1 1]
 [1 1 1]]


In [18]:
f = np.full((3, 2), 10) #заполняет массив указанным значением
print(f)

[[10 10]
 [10 10]
 [10 10]]


## функции создания матриц

In [29]:
a = np.matrix('1 2 3 4') # создает матрицу 1х4 из строки
a

matrix([[1, 2, 3, 4]])

In [31]:
a = np.matrix('1 2 3 ; 4 5 6') # создает матрицу 2х3 из строки
a

matrix([[1, 2, 3],
        [4, 5, 6]])

In [33]:
a = np.matrix([1, 2, 3]) # создает матрицу 1х3 из списка
print(a)
a = np.matrix([(1, 2, 3), (4, 5, 6)]) # создает матрицу 2х3 из списка
print(a)

[[1 2 3]]
[[1 2 3]
 [4 5 6]]


In [35]:
d = np.diag([1,2,3]) # создает матрицу с указанной диагональю
print(d)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [37]:
d = np.diag([(1, 2, 3), (4, 5, 6), (7, 8, 9)]) # возвращает элементы на диагонали
print(d)

[1 5 9]


In [39]:
d = np.diagflat([(1, 2), (3, 4), (5, 6)]) # все элементы становятся на диагональ
print(d)

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [41]:
t = np.tri(4, dtype= 'int8') # создает треугольную матрицу
print(t)
t = np.tri(4, 2, dtype= 'int8') # создает треугольную матрицу
print(t)

[[1 0 0 0]
 [1 1 0 0]
 [1 1 1 0]
 [1 1 1 1]]
[[1 0]
 [1 1]
 [1 1]
 [1 1]]


In [43]:
print(np.tril(a))
print(np.triu(a))

[[1 0 0]
 [4 5 0]]
[[1 2 3]
 [0 5 6]]


## Функции формирования числовых диапазонов

In [46]:
n = np.arange(5) # как range
print(n)
n = np.arange(0, 5, 0.5) # 0.5 это шаг
print(n)

[0 1 2 3 4]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [48]:
n = np.linspace(0, np.pi, 3) #делит интервал на отрезки
print(n)

[0.         1.57079633 3.14159265]


## Функции формирования массивов на основе данных

In [51]:
a = np.array([(1, 2), (3, 4)])
print(a)

[[1 2]
 [3 4]]


In [53]:
b = np.copy(a) #копирует массив
print(b)

[[1 2]
 [3 4]]


In [55]:
def getRange(x, y): # x - индекс строки, y - индекс столбца
    return 100 * x + y
a = np.fromfunction(getRange, (2, 2))
print(a)

[[  0.   1.]
 [100. 101.]]


In [57]:
a = np.fromiter("hello", dtype= 'U1') # формирует массив из любого итерируемого объекта
print(a)

['h' 'e' 'l' 'l' 'o']


In [59]:
a = np.fromstring('1 2 3', dtype= 'int16', sep= ' ') # формирует массив из строк
print(a)

[1 2 3]


In [61]:
a = np.matrix([(1, 2, 3), (4, 5, 6)]) # создает матрицу 2х3 из списка
print(a)

[[1 2 3]
 [4 5 6]]


In [65]:
a = np.array( [ [(1, 2), (3, 4), (5, 6), (7, 8)], [(1, 2), (3, 4), (5, 6), (7, 8)] ] )
print(a)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]

 [[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [67]:
a = 10 * (np.array( ((7, 8, 9),(10, 11, 12)) ))
print(a)
print(a[0, 2])
a[0, 2] = 10
print(a)

[[ 70  80  90]
 [100 110 120]]
90
[[ 70  80  10]
 [100 110 120]]
