In [3]:
import numpy as np

In [5]:
a = np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
print(a)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [7]:
print(a.dtype) #тип данных в массиве
a.dtype = np.int8() # изменение типа данных в массиве
print(a)

float64
[-102 -103 -103 -103 -103 -103  -71   63 -102 -103 -103 -103 -103 -103
  -55   63   51   51   51   51   51   51  -45   63 -102 -103 -103 -103
 -103 -103  -39   63    0    0    0    0    0    0  -32   63   51   51
   51   51   51   51  -29   63  102  102  102  102  102  102  -26   63
 -102 -103 -103 -103 -103 -103  -23   63  -51  -52  -52  -52  -52  -52
  -20   63]


In [9]:
print(a.size) # размер массива

72


In [11]:
a.dtype = np.float64()
print(a.itemsize) # сколько байт занимает один элемент массива

8


In [13]:
b = np.ones( (3, 4, 5) )
print(b)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [15]:
print(b.ndim) #узнать количество осей массива, т.е. одномерный массив, двумерный или трехмерный

3


In [17]:
print(b.shape) #узнать размерность массива

(3, 4, 5)


In [19]:
#можем менять размерность массива, главное,
# чтобы общее число элементов оставалось прежним.
b.shape = 60
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [21]:
b.shape = (4, 15)
print(b)
b.shape = (12, 5)
print(b)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
c = b.reshape(3, 2, 10)
print(c)
d = c.copy()
#метод reshape возвращает массив с новой указанной размерностью (прежний массив остается без изменений). 
#В результате, переменная c будет ссылаться на массив размерами 3x2x10, а переменная b – на массив 12x5. 
#Но данные при этом, будут использоваться одни и те же

[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]]


In [27]:
b[0, 0] = 10
print(b)
print(c)

[[10.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[[10.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]]


In [29]:
d = b.T #транспонирование 
print(b)
print(d)

[[10.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[10.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [31]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = a
a.shape = 3,3
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = a.view() #создает копию представления
print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [35]:
a.shape = 3, 3
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [37]:
# Создание копии массива
a = np.array([1,2,3,4,5,6,7,8,9])

b = np.array(a)
print(b)

[1 2 3 4 5 6 7 8 9]


In [39]:
c = a.copy()
print(c)

[1 2 3 4 5 6 7 8 9]
