In [2]:
import numpy as np
#Функции hstack и vstack

In [59]:
a = np.array([(1, 2), (3, 4)])
b = np.array([(5, 6), (7, 8)])

In [61]:
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [63]:
print(np.hstack([a, b])) # объединение по горизонтали, по axis1
print(np.vstack([a,b])) # по вертикали, по строкам, по axis0

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [13]:
a = np.arange(1, 13)
b = np.arange(13, 26)
a.resize(3, 3, 2)
b.resize(3, 3, 2)

In [15]:
print(a)
print(b)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[ 0  0]
  [ 0  0]
  [ 0  0]]]
[[[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]

 [[25  0]
  [ 0  0]
  [ 0  0]]]


In [19]:
c0 = np.concatenate([a, b], axis=0) # размерность 6x3x2
c1 = np.concatenate([a, b], axis=1) # размерность 3x6x2
c2 = np.concatenate([a, b], axis=2) # размерность 3x3x4

In [21]:
print(c0)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[ 0  0]
  [ 0  0]
  [ 0  0]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]

 [[25  0]
  [ 0  0]
  [ 0  0]]]


In [23]:
print(c1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [13 14]
  [15 16]
  [17 18]]

 [[ 7  8]
  [ 9 10]
  [11 12]
  [19 20]
  [21 22]
  [23 24]]

 [[ 0  0]
  [ 0  0]
  [ 0  0]
  [25  0]
  [ 0  0]
  [ 0  0]]]


In [25]:
print(c2)

[[[ 1  2 13 14]
  [ 3  4 15 16]
  [ 5  6 17 18]]

 [[ 7  8 19 20]
  [ 9 10 21 22]
  [11 12 23 24]]

 [[ 0  0 25  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]]


In [27]:
print(np.r_[ [1, 2, 3], 4, 5])  # список + дополнительные элементы

[1 2 3 4 5]


In [29]:
print(np.r_[ 1:9, 90, 100]) # срез + два элемента

[  1   2   3   4   5   6   7   8  90 100]


In [31]:
print(np.r_[ np.array([1,2,3]), np.array([4,5,6])]) # объединение двух массивов

[1 2 3 4 5 6]


In [33]:
print(np.r_[ [(1,2,3), (4,5,6)], [(7,8,9)] ]) # объединение двумерного и одномерного списков

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
np.c_[1:5] # объединение выполняется по второй оси axis1

array([[1],
       [2],
       [3],
       [4]])

In [41]:
np.c_[ [1, 2, 3], [4, 5, 6]]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [43]:
np.c_[ [(1,2,3), (4,5,6)], [[7],[8]] ]

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [45]:
a = np.arange(18)
a.resize(3, 3, 2)
print(a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]


In [47]:
print(np.array_split(a, 2, axis=2))

[array([[[ 0],
        [ 2],
        [ 4]],

       [[ 6],
        [ 8],
        [10]],

       [[12],
        [14],
        [16]]]), array([[[ 1],
        [ 3],
        [ 5]],

       [[ 7],
        [ 9],
        [11]],

       [[13],
        [15],
        [17]]])]


In [49]:
print(np.array_split(a, 3, axis=0))

[array([[[0, 1],
        [2, 3],
        [4, 5]]]), array([[[ 6,  7],
        [ 8,  9],
        [10, 11]]]), array([[[12, 13],
        [14, 15],
        [16, 17]]])]


In [51]:
print(a)
print(np.array_split(a, 3, axis=1))

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]
[array([[[ 0,  1]],

       [[ 6,  7]],

       [[12, 13]]]), array([[[ 2,  3]],

       [[ 8,  9]],

       [[14, 15]]]), array([[[ 4,  5]],

       [[10, 11]],

       [[16, 17]]])]
