## Индексация и срезы одномерных массивов

In [1]:
import numpy as np

In [3]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [7]:
print(a[2])
print(a[-1])
print(a[0])

2
11
0


In [11]:
a[0] = 100
print(a)

[100   1   2   3   4   5   6   7   8   9  10  11]


In [13]:
b = a[2:4]
print(b)

[2 3]


In [17]:
b[0] = -100
print(b)
print(a)

[-100    3]
[ 100    1 -100    3    4    5    6    7    8    9   10   11]


In [25]:
print(a[3:])
print(a[5:])
print(a[:])
print(a[1:6:2])

[ 3  4  5  6  7  8  9 10 11]
[ 5  6  7  8  9 10 11]
[ 100    1 -100    3    4    5    6    7    8    9   10   11]
[1 3 5]


In [37]:
a[:4] = [-1, -2, -3,- 4]
print(a)

[-1 -2 -3 -4 10  5 20  7 30  9 40 11]


In [39]:
a[4::2] = np.array([10, 20, 30, 40])
print(a)

[-1 -2 -3 -4 10  5 20  7 30  9 40 11]


In [41]:
for x in a:
    print(x, sep= ' ', end=' ')

-1 -2 -3 -4 10 5 20 7 30 9 40 11 

## Индексация и срезы многомерных массивов

In [45]:
x = np.array([(1, 2, 3), (10, 20, 30), (100, 200, 300)])
print(x)

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]]


In [63]:
print(x[1, 1])
print(x[-1, -1])
print(x[0])
print(x[0, :])
print(x[0, :2])
print(x[:, 1])

20
300
[1 2 3]
[1 2 3]
[1 2]
[  2  20 200]


In [65]:
for row in x:
    for val in row:
        print(val, end=' ')
    print()

1 2 3 
10 20 30 
100 200 300 


In [67]:
for val in x.flat:
    print(val, end= " ")

1 2 3 10 20 30 100 200 300 

In [69]:
a = np.arange(1, 82).reshape(3, 3, 3, 3)
print(a[1, 2, 0, 1])

47


In [71]:
print(a[:, 1, :, :])

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]]

 [[64 65 66]
  [67 68 69]
  [70 71 72]]]


In [73]:
print(a[:, :, 0, 0])

[[ 1 10 19]
 [28 37 46]
 [55 64 73]]


In [75]:
print(a[0:2, 0:2, 1, 1]) # матрица 2x2

[[ 5 14]
 [32 41]]


# Списочная индексация

In [78]:
a = np.arange(1, 9)
print(a)

[1 2 3 4 5 6 7 8]


In [82]:
b = a[[0]] # копия
print(b)

[1]


In [86]:
b = a[[0, 1, 7, 5]] # возвращает элементы с указанными индексами
print(b)

[1 2 8 6]


In [88]:
b = a[[0, 0, 1, 1, 1, 2, 3, 4, 5, 6, 7]]
print(b)

[1 1 2 2 2 3 4 5 6 7 8]


In [94]:
a[[0, 1, 7, 5]] = [10, 20, 30, 40] # в элементы массива a с индексами 0,1 и т.д. заносятся значения 10, 20 и т.д.
print(a)

[10 20  3  4  5 40  7 30]


In [103]:
indx = [0, 0, 1, 1, 1, 2] # это индексы
print(a[indx])

[10 10 20 20 20  3]


In [105]:
bIndx = [True, True, False, False, False, True, False, False] # где True, возвращает значение  
print(a[bIndx])

[10 20 40]


In [109]:
i = a > 5
print(i)
print(a[i])

[ True  True False False False  True  True  True]
[10 20 40  7 30]


In [111]:
print(a[a > 5])

[10 20 40  7 30]


## Списочная индексация и многомерные массивы

In [115]:
a = np.arange(1, 9)
i = np.array([[0, 1], [2, 3]]) # тоже индексы
print(a[i])

[[1 2]
 [3 4]]


In [119]:
a = np.arange(1, 13).reshape(3, 4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [123]:
indx = [2, 1, 0] # здесь индексы обозначают номера строк двумерного массива
print(a[indx])

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [127]:
indx = np.array([[1, 0], [2, 1]]) # тоже порядок строк
print(a[indx])

[[[ 5  6  7  8]
  [ 1  2  3  4]]

 [[ 9 10 11 12]
  [ 5  6  7  8]]]


In [129]:
i0 = [0, 1]
i1 = [1, 2]
print(a[i0, i1])

[2 7]


In [131]:
print(a[:, [1, 2]])

[[ 2  3]
 [ 6  7]
 [10 11]]


In [135]:
print(a[[0, 1], 1])

[2 6]


## Изменение массивов через списочную индексацию

In [140]:
a = np.arange(7)
print(a)

[0 1 2 3 4 5 6]


In [142]:
a[[0, 4, 6]] = [-1, -2, -3]
print(a)

[-1  1  2  3 -2  5 -3]


In [144]:
a[[0, 1, 2]] += 1
print(a)

[ 0  2  3  3 -2  5 -3]


In [152]:
print(a[[0, 1, 2]])

[0 2 3]
