In [6]:
import numpy as np

## Массивы и числа

In [8]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [10]:
print(-a)

[-1 -2 -3]


In [12]:
print(a - 3)

[-2 -1  0]


In [14]:
print(a + 2)

[3 4 5]


In [16]:
print(a * 5)

[ 5 10 15]


In [18]:
print(a / 2)

[0.5 1.  1.5]


In [20]:
print(a // 2)

[0 1 1]


In [22]:
print(a ** 3)

[ 1  8 27]


## Массивы и массивы

In [30]:
b = np.array([3, 4, 5])
print(b)

[3 4 5]


In [32]:
print(a + b)
print(a * b)
print(a / b)
print(a // b)
print(a ** b)

[4 6 8]
[ 3  8 15]
[0.33333333 0.5        0.6       ]
[0 0 0]
[  1  16 243]


In [ ]:
#транслирование массивов

In [36]:
b = np.arange(1, 7)
b.resize(2, 3)
print(a)
print(b)
print(a + b)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[2 4 6]
 [5 7 9]]


## Расширенные аналоги

In [40]:
a = np.array([1, 2, 6, 8])
print(a)

[1 2 6 8]


In [44]:
a +=5
print(a)

[11 12 16 18]


In [46]:
a -= 5
print(a)

[ 6  7 11 13]


In [50]:
b = np.ones(4)
b *= a
print(b)

[ 6.  7. 11. 13.]


In [ ]:
a +=b # несоответствие типов

In [52]:
print((a + b) * 5 -10)

[ 50.  60. 100. 120.]
