In [3]:
import numpy as np

In [5]:
a = np.array([1, 2, 3, 10, 20, 30])
print(a)

[ 1  2  3 10 20 30]


In [9]:
print(a > 5)
print(a[a > 5])

[False False False  True  True  True]
[10 20 30]


In [13]:
b = np.array([1, 2, 3, 4, 5, 6])
print(b)

[1 2 3 4 5 6]


In [17]:
print(a == b)
print(a != b)

[ True  True  True False False False]
[False False False  True  True  True]


## Функции greater, less, equal

In [ ]:
#greater(a, b) – выполняет сравнение a > b;
#less(a, b) – выполняет сравнение a < b;
#equal(a, b) – выполняет сравнение a == b.

In [24]:
print(np.greater(a, b))

[False False False  True  True  True]


In [26]:
print(np.less(a, b))

[False False False False False False]


In [30]:
print(np.equal(a, b))

[ True  True  True False False False]


## Функции array_equal, all и any

In [32]:
print(np.array_equal(a, b))

False


In [38]:
if np.array_equal(a, b):
    print("a == b")

In [44]:
print(np.any(a > 5)) # хотя бы один элемент больше 5

True


In [46]:
print(np.any(a == 5))

False


In [52]:
print(np.all(a > 5)) # все элементы массива а больше 5

False


## Значения -inf, inf и nan

In [55]:
print(a / 0)

[inf inf inf inf inf inf]


C:\Users\ryagu\AppData\Local\Temp\ipykernel_20196\3695248558.py:1: RuntimeWarning: divide by zero encountered in divide
  print(a / 0)


In [57]:
b = np.array([1, 2, np.inf])
print(b)

[ 1.  2. inf]


In [61]:
print(b * 0) # nan - not a number (не число)

[ 0.  0. nan]


C:\Users\ryagu\AppData\Local\Temp\ipykernel_20196\3326190063.py:1: RuntimeWarning: invalid value encountered in multiply
  print(b * 0) # nan - not a number (не число)


In [67]:
c = b*0
print(c)
print(c.sum())

[ 0.  0. nan]
nan


C:\Users\ryagu\AppData\Local\Temp\ipykernel_20196\2315904396.py:1: RuntimeWarning: invalid value encountered in multiply
  c = b*0


## Функции isnan и isinf

In [71]:
b = np.array([1, 2, np.nan, np.inf, -np.inf])
print(b)

[  1.   2.  nan  inf -inf]


In [75]:
print(np.isinf(b))
print(np.isnan(b))

[False False False  True  True]
[False False  True False False]


In [80]:
#можно исключить нечисловые элементы из массива
indx = np.isinf(b)
print(b[~indx])  #  ~indx инвертирует булевы значения

[ 1.  2. nan]


## Дополнительные функции: isfinite, iscomplex, isreal

In [85]:
print(np.isfinite(b)) # True если элемент число

[ True  True False False False]


In [91]:
a = np.array([1+2j, 3-4j, 5])
print(np.iscomplex(a))
print(np.isreal(a))

[ True  True False]
[False False  True]


In [95]:
print(np.isreal(b)) # специальные значения nan и inf отмечаются как действительные

[ True  True  True  True  True]


## Функции logical_and, logical_or, logical_not и logical_xor


In [98]:
X = np.array([True, False, True, False])
Y = np.array([True, True, False, False])

In [114]:
print(np.logical_and(X, Y)) # True, если принимают одинаковые значения 

[ True False False False]


In [112]:
print(np.logical_or(X, Y)) # True, если принимают разные значения 

[ True  True  True False]


In [108]:
print(np.logical_not(X)) # инвертирует 

[False  True False  True]


In [110]:
print(np.logical_xor(X, Y))

[False  True  True False]


In [116]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([5, 4, 3, 2, 1])

In [118]:
print(np.logical_and(x > 2, y > 2))

[False False  True False False]


In [120]:
print(np.logical_or(x > 2, y > 2))

[ True  True  True  True  True]
